# Question 1

In [1]:
import numpy as np

In [8]:
a = np.empty((3,3,3))
a

array([[[0.0e+000, 0.0e+000, 7.9e-323],
        [0.0e+000, 0.0e+000, 0.0e+000],
        [0.0e+000, 0.0e+000, 0.0e+000]],

       [[0.0e+000, 0.0e+000, 0.0e+000],
        [0.0e+000, 0.0e+000, 0.0e+000],
        [0.0e+000, 4.4e-323, 0.0e+000]],

       [[0.0e+000, 0.0e+000, 0.0e+000],
        [0.0e+000, 0.0e+000, 0.0e+000],
        [2.5e-323, 0.0e+000, 0.0e+000]]])

In [9]:
a.shape

(3, 3, 3)

# Question 2

In [62]:
x = np.zeros ((3,3), dtype=int)
x[1::2, ::2]= 1
x[::2, 1::2] = 1
print (x)

[[0 1 0]
 [1 0 1]
 [0 1 0]]


# Question 3

In [20]:
x = np.ones((3,3))
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Question 4

In [22]:
a= np.random.random((3,3))
print("Original Array:")
print(a)
amax, amin = a.max(), a.min()
a = (a - amin)/(amax - amin)
print("After normalization:")
print(a)

Original Array:
[[0.66718167 0.22726503 0.25906241]
 [0.42319557 0.33071414 0.91496292]
 [0.11814032 0.59236678 0.70085336]]
After normalization:
[[0.68903838 0.13694981 0.17685503]
 [0.38283961 0.26677684 1.        ]
 [0.         0.59514685 0.73129583]]


# Question 5

In [23]:
arr1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",arr1)
arr2 = [10, 30, 40]
print("Array2: ",arr2)
print("Common values between two arrays:")
print(np.intersect1d(arr1, arr2))


Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# Question 6

In [24]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)


Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# Question 7

In [26]:
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)


First array:
[1 0 0 0 0 0]
Second array:
[0 1 1 0 0 1]
equal or not!
False


# Question 8

In [28]:
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)


Original array:
[0.90199604 0.18173897 0.69672312 0.39422397 0.77966022 0.6971766
 0.58101463 0.94616648 0.95659584 0.62209558]
Maximum value replaced by 0:
[0.90199604 0.18173897 0.69672312 0.39422397 0.77966022 0.6971766
 0.58101463 0.94616648 0.         0.62209558]


# Question 9

In [37]:
import numpy as np
np.sys.maxsize
x = np.zeros((4, 4))
print(x)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Question 10

In [38]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(4, 4)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)


Original matrix:

[[0.01601812 0.21345122 0.50850008 0.10196756]
 [0.95396317 0.57242165 0.55451543 0.34155682]
 [0.03280023 0.47972776 0.04412714 0.58380467]
 [0.34080383 0.77622584 0.65873628 0.4610724 ]]

Subtract the mean of each row of the said matrix:

[[-0.19396612  0.00346698  0.29851583 -0.10801669]
 [ 0.3483489  -0.03319261 -0.05109884 -0.26405745]
 [-0.25231472  0.19461281 -0.24098781  0.29868972]
 [-0.21840576  0.21701625  0.09952669 -0.09813719]]


# Question 11

In [39]:
a = np.ones(10)
b = np.random.randint(0,len(a),20)
a += np.bincount(b, minlength=len(a))
print(a)


[4. 2. 3. 2. 4. 5. 2. 2. 4. 2.]


# Question 12

In [43]:
x = np.random.randint(0,10,(3,3))
y= np.random.randint(0,10,(3,3))

np.diag(np.dot(x, y))

array([72, 74, 78])

# Question 13

In [48]:
a = np.random.randint(0,10,50)
print (a)
print('rank:', np.bincount(a).argmax())


[6 1 4 1 3 6 8 2 2 2 7 3 2 0 1 4 2 4 9 5 7 0 7 2 5 6 3 1 9 1 7 1 4 5 1 8 9
 3 3 0 6 2 5 3 5 6 6 0 4 8]
rank: 1


# Question 14

In [51]:
Z = np.arange(542)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

[537 538 539 540 541]


# Question 15

In [55]:
a = np.array([("Lets", 2.5, 3),
              ("Upgrade", 3.6, 2)])
b = np.core.records.fromarrays(a.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
b

rec.array([(b'Lets', 2.5, 3), (b'Upgrade', 3.6, 2)],
          dtype=[('col1', 'S8'), ('col2', '<f8'), ('col3', '<i8')])